// Canonical site origin + URL helpers for SEO metadata (canonical links, OG/Twitter
// images, sitemap, robots). Centralized here so every absolute URL is built one way.
//
// The origin comes from NEXT_PUBLIC_SITE_URL (set per environment in Vercel).
// Until that var is set there is no owned production domain, so the site is
// treated as NOT launched for SEO: robots.txt disallows everything and every
// page carries a noindex meta (see robots.ts and app/layout.tsx). Setting
// NEXT_PUBLIC_SITE_URL is the SEO go-live switch. Absolute URLs meanwhile fall
// back to the deployment's own origin (Vercel injects the bare host in
// VERCEL_PROJECT_PRODUCTION_URL) so they at least point somewhere we control,
// never at a domain we do not own.
const RAW_SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ??
  (process.env.VERCEL_PROJECT_PRODUCTION_URL
    ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
    : "http://localhost:3000");

/**
 * True once NEXT_PUBLIC_SITE_URL is set — the signal that a real production
 * domain exists and search engines may index the site. Gates robots.txt and
 * the root noindex meta.
 */
export const IS_LAUNCHED = Boolean(process.env.NEXT_PUBLIC_SITE_URL);

/** Absolute site origin, no trailing slash (e.g. "https://pinprint.com"). */
export const SITE_URL = RAW_SITE_URL.replace(/\/+$/, "");

/** Resolve a root-relative path to an absolute URL, e.g. "/compare" → "https://…/compare". */
export function absoluteUrl(path: string): string {
  return new URL(path, SITE_URL).toString();
}

/**
 * Default Open Graph / Twitter share image: a purpose-built 1200×630 crop of
 * the hero lifestyle scene (generated by scripts/compose-scenes.ts).
 */
export const OG_IMAGE = "/showcase/og-card.png";
